(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type numbers = {
  value : int64;
}

module List_numbers = struct
  type params = unit
  type row = {
    value : int64;
  }

  let request =
    let open Caqti_request.Infix in
    ((Caqti_type.unit) ->* (Caqti_type.int64)) "SELECT value\nFROM numbers\nORDER BY value"

  let execute (module Db : Caqti_async.CONNECTION) (_params : params) =
    Db.collect_list request ()
    |> Async_kernel.Deferred.map ~f:(Result.map (List.map (fun v_value -> { value = v_value })))

  let fold (module Db : Caqti_async.CONNECTION) (_params : params) ~init ~f =
    Db.fold request (fun raw acc -> f ((fun v_value -> { value = v_value }) raw) acc) () init
end

