(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type one
type many
type exec
type exec_rows

type ('params, 'result, 'cardinality) query =
  | One :
      (string *
       ((module Caqti_async.CONNECTION) ->
        'params ->
        ('result, Caqti_error.t) result Async_kernel.Deferred.t)) ->
      ('params, 'result, one) query
  | Many :
      (string *
       ((module Caqti_async.CONNECTION) ->
        'params ->
        ('result, Caqti_error.t) result Async_kernel.Deferred.t)) ->
      ('params, 'result, many) query
  | Exec :
      (string *
       ((module Caqti_async.CONNECTION) ->
        'params ->
        ('result, Caqti_error.t) result Async_kernel.Deferred.t)) ->
      ('params, 'result, exec) query
  | Exec_rows :
      (string *
       ((module Caqti_async.CONNECTION) ->
        'params ->
        ('result, Caqti_error.t) result Async_kernel.Deferred.t)) ->
      ('params, 'result, exec_rows) query

type numbers = {
  value : int64;
}

(** Query [ListNumbers] (returns zero or more rows). *)
module ListNumbers : sig
  (** Stable operation name declared in the SQL source. *)
  val operation : string

  type params = unit
  type row = {
    value : int64;
  }

  (** Execute [ListNumbers]. *)
  val execute :
    (module Caqti_async.CONNECTION) ->
    params ->
    (row list, [> Caqti_error.call_or_retrieve ]) result Async_kernel.Deferred.t

  (** Named query descriptor for database helpers. *)
  val query : (params, row list, many) query

  (** Fold rows without materializing the complete result list. *)
  val fold :
    (module Caqti_async.CONNECTION) ->
    params ->
    init:'a ->
    f:(row -> 'a -> 'a) ->
    ('a, [> Caqti_error.call_or_retrieve ]) result Async_kernel.Deferred.t
end

