(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type numbers = {
  value : int64;
}

module ListNumbers = struct
  let operation = "ListNumbers"

  type params = unit
  type row = {
    value : int64;
  }

  let sql =
    {sql|SELECT value
FROM numbers
ORDER BY value|sql}

  let params_type =
    Caqti_type.unit

  let row_type =
    Caqti_type.int64

  let encode_params (_params : params) =
    ()

  let decode_row v_value =
    { value = v_value }

  let request =
    let open Caqti_request.Infix in
    (params_type ->* row_type) sql

  let execute (module Db : Caqti_async.CONNECTION) (params : params) =
    Db.collect_list request (encode_params params)
    |> Async_kernel.Deferred.map ~f:(Result.map (List.map decode_row))

  let fold (module Db : Caqti_async.CONNECTION) (params : params) ~init ~f =
    Db.fold request (fun raw acc -> f (decode_row raw) acc) (encode_params params) init

  let query = (operation, execute)
end

