(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type numbers = {
  value : int64;
}

module List_numbers : sig
  type params = unit
  type row = {
    value : int64;
  }

  val execute :
    (module Caqti_async.CONNECTION) ->
    params ->
    (row list, [> Caqti_error.call_or_retrieve ]) result Async_kernel.Deferred.t

  val fold :
    (module Caqti_async.CONNECTION) ->
    params ->
    init:'a ->
    f:(row -> 'a -> 'a) ->
    ('a, [> Caqti_error.call_or_retrieve ]) result Async_kernel.Deferred.t
end

