(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type todos = {
  id : int64;
  title : string;
  completed : bool;
  todo_order : int32;
}

module CreateTodo = struct
  type params = {
    title : string;
    completed : bool;
    todo_order : int32;
  }
  type row = {
    id : int64;
    title : string;
    completed : bool;
    order : int32;
  }

  let sql =
    {sql|INSERT INTO todos (title, completed, todo_order)
VALUES (?, ?, ?)
RETURNING todos.id, todos.title, todos.completed, todos.todo_order AS "order"|sql}

  let params_type =
    Caqti_type.t2 (Caqti_type.t2 (Caqti_type.string) (Caqti_type.bool)) (Caqti_type.int32)

  let row_type =
    Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Caqti_type.bool)) (Caqti_type.int32)

  let encode_params (params : params) =
    ((params.title, params.completed), params.todo_order)

  let decode_row (((v_id, v_title), v_completed), v_order) =
    { id = v_id; title = v_title; completed = v_completed; order = v_order }

  let request =
    let open Caqti_request.Infix in
    (params_type ->! row_type) sql

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.find request (encode_params params)
    |> Lwt.map (Result.map decode_row)
end

module ListTodos = struct
  type params = unit
  type row = {
    id : int64;
    title : string;
    completed : bool;
    order : int32;
  }

  let sql =
    {sql|SELECT id, title, completed, todo_order AS "order"
FROM todos
ORDER BY id|sql}

  let params_type =
    Caqti_type.unit

  let row_type =
    Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Caqti_type.bool)) (Caqti_type.int32)

  let encode_params (_params : params) =
    ()

  let decode_row (((v_id, v_title), v_completed), v_order) =
    { id = v_id; title = v_title; completed = v_completed; order = v_order }

  let request =
    let open Caqti_request.Infix in
    (params_type ->* row_type) sql

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.collect_list request (encode_params params)
    |> Lwt.map (Result.map (List.map decode_row))

  let fold (module Db : Caqti_lwt.CONNECTION) (params : params) ~init ~f =
    Db.fold request (fun raw acc -> f (decode_row raw) acc) (encode_params params) init
end

module GetTodo = struct
  type params = {
    id : int64;
  }
  type row = {
    id : int64;
    title : string;
    completed : bool;
    order : int32;
  }

  let sql =
    {sql|SELECT id, title, completed, todo_order AS "order"
FROM todos
WHERE id = ?|sql}

  let params_type =
    Caqti_type.int64

  let row_type =
    Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Caqti_type.bool)) (Caqti_type.int32)

  let encode_params (params : params) =
    params.id

  let decode_row (((v_id, v_title), v_completed), v_order) =
    { id = v_id; title = v_title; completed = v_completed; order = v_order }

  let request =
    let open Caqti_request.Infix in
    (params_type ->* row_type) sql

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.collect_list request (encode_params params)
    |> Lwt.map (Result.map (List.map decode_row))

  let fold (module Db : Caqti_lwt.CONNECTION) (params : params) ~init ~f =
    Db.fold request (fun raw acc -> f (decode_row raw) acc) (encode_params params) init
end

module PatchTodo = struct
  type params = {
    title : string option;
    completed : bool option;
    todo_order : int32 option;
    id : int64;
  }
  type row = {
    id : int64;
    title : string;
    completed : bool;
    order : int32;
  }

  let sql =
    {sql|UPDATE todos
SET title = COALESCE(?, title),
    completed = COALESCE(?, completed),
    todo_order = COALESCE(?, todo_order)
WHERE id = ?
RETURNING todos.id, todos.title, todos.completed, todos.todo_order AS "order"|sql}

  let params_type =
    Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.option (Caqti_type.string)) (Caqti_type.option (Caqti_type.bool))) (Caqti_type.option (Caqti_type.int32))) (Caqti_type.int64)

  let row_type =
    Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Caqti_type.bool)) (Caqti_type.int32)

  let encode_params (params : params) =
    (((params.title, params.completed), params.todo_order), params.id)

  let decode_row (((v_id, v_title), v_completed), v_order) =
    { id = v_id; title = v_title; completed = v_completed; order = v_order }

  let request =
    let open Caqti_request.Infix in
    (params_type ->* row_type) sql

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.collect_list request (encode_params params)
    |> Lwt.map (Result.map (List.map decode_row))

  let fold (module Db : Caqti_lwt.CONNECTION) (params : params) ~init ~f =
    Db.fold request (fun raw acc -> f (decode_row raw) acc) (encode_params params) init
end

module DeleteTodo = struct
  type params = {
    id : int64;
  }

  let sql =
    {sql|DELETE FROM todos WHERE id = ?|sql}

  let params_type =
    Caqti_type.int64

  let encode_params (params : params) =
    params.id

  let request =
    let open Caqti_request.Infix in
    (params_type ->. Caqti_type.unit) sql

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.exec request (encode_params params)
end

module DeleteAllTodos = struct
  type params = unit

  let sql =
    {sql|DELETE FROM todos|sql}

  let params_type =
    Caqti_type.unit

  let encode_params (_params : params) =
    ()

  let request =
    let open Caqti_request.Infix in
    (params_type ->. Caqti_type.unit) sql

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.exec request (encode_params params)
end

