(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type one
type many
type exec
type exec_rows

type ('params, 'result, 'cardinality) query =
  | One :
      (string *
       ((module Caqti_lwt.CONNECTION) ->
        'params ->
        ('result, Caqti_error.t) result Lwt.t)) ->
      ('params, 'result, one) query
  | Many :
      (string *
       ((module Caqti_lwt.CONNECTION) ->
        'params ->
        ('result, Caqti_error.t) result Lwt.t)) ->
      ('params, 'result, many) query
  | Exec :
      (string *
       ((module Caqti_lwt.CONNECTION) ->
        'params ->
        ('result, Caqti_error.t) result Lwt.t)) ->
      ('params, 'result, exec) query
  | Exec_rows :
      (string *
       ((module Caqti_lwt.CONNECTION) ->
        'params ->
        ('result, Caqti_error.t) result Lwt.t)) ->
      ('params, 'result, exec_rows) query

type todos = {
  id : int64;
  title : string;
  completed : bool;
  todo_order : int32;
}

type todo_row = {
  id : int64;
  title : string;
  completed : bool;
  order : int32;
}

(** Query [CreateTodo] (returns exactly one row). *)
module CreateTodo : sig
  (** Stable operation name declared in the SQL source. *)
  val operation : string

  type params = {
    title : string;
    completed : bool;
    todo_order : int32;
  }
  type row = todo_row

  (** Execute [CreateTodo]. *)
  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  (** Named query descriptor for database helpers. *)
  val query : (params, row, one) query
end

(** Query [ListTodos] (returns zero or more rows). *)
module ListTodos : sig
  (** Stable operation name declared in the SQL source. *)
  val operation : string

  type params = unit
  type row = todo_row

  (** Execute [ListTodos]. *)
  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row list, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  (** Named query descriptor for database helpers. *)
  val query : (params, row list, many) query

  (** Fold rows without materializing the complete result list. *)
  val fold :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    init:'a ->
    f:(row -> 'a -> 'a) ->
    ('a, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

(** Query [GetTodo] (returns zero or more rows). *)
module GetTodo : sig
  (** Stable operation name declared in the SQL source. *)
  val operation : string

  type params = {
    id : int64;
  }
  type row = todo_row

  (** Execute [GetTodo]. *)
  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row list, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  (** Named query descriptor for database helpers. *)
  val query : (params, row list, many) query

  (** Fold rows without materializing the complete result list. *)
  val fold :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    init:'a ->
    f:(row -> 'a -> 'a) ->
    ('a, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

(** Query [PatchTodo] (returns zero or more rows). *)
module PatchTodo : sig
  (** Stable operation name declared in the SQL source. *)
  val operation : string

  type params = {
    title : string option;
    completed : bool option;
    todo_order : int32 option;
    id : int64;
  }
  type row = todo_row

  (** Execute [PatchTodo]. *)
  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row list, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  (** Named query descriptor for database helpers. *)
  val query : (params, row list, many) query

  (** Fold rows without materializing the complete result list. *)
  val fold :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    init:'a ->
    f:(row -> 'a -> 'a) ->
    ('a, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

(** Query [DeleteTodo] (executes without returning rows). *)
module DeleteTodo : sig
  (** Stable operation name declared in the SQL source. *)
  val operation : string

  type params = {
    id : int64;
  }

  (** Execute [DeleteTodo]. *)
  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (unit, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  (** Named query descriptor for database helpers. *)
  val query : (params, unit, exec) query
end

(** Query [DeleteAllTodos] (executes without returning rows). *)
module DeleteAllTodos : sig
  (** Stable operation name declared in the SQL source. *)
  val operation : string

  type params = unit

  (** Execute [DeleteAllTodos]. *)
  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (unit, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  (** Named query descriptor for database helpers. *)
  val query : (params, unit, exec) query
end

