(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type todos = {
  id : int64;
  title : string;
  completed : bool;
  todo_order : int32;
}

module Create_todo = struct
  type params = {
    title : string;
    completed : bool;
    todo_order : int32;
  }
  type row = {
    id : int64;
    title : string;
    completed : bool;
    order : int32;
  }

  let request =
    let open Caqti_request.Infix in
    ((Caqti_type.t2 (Caqti_type.t2 (Caqti_type.string) (Caqti_type.bool)) (Caqti_type.int32)) ->! (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Caqti_type.bool)) (Caqti_type.int32))) "INSERT INTO todos (title, completed, todo_order)\nVALUES (?, ?, ?)\nRETURNING todos.id, todos.title, todos.completed, todos.todo_order AS \"order\""

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.find request ((params.title, params.completed), params.todo_order)
    |> Lwt.map (Result.map (fun (((v_id, v_title), v_completed), v_order) -> { id = v_id; title = v_title; completed = v_completed; order = v_order }))
end

module List_todos = struct
  type params = unit
  type row = {
    id : int64;
    title : string;
    completed : bool;
    order : int32;
  }

  let request =
    let open Caqti_request.Infix in
    ((Caqti_type.unit) ->* (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Caqti_type.bool)) (Caqti_type.int32))) "SELECT id, title, completed, todo_order AS \"order\"\nFROM todos\nORDER BY id"

  let execute (module Db : Caqti_lwt.CONNECTION) (_params : params) =
    Db.collect_list request ()
    |> Lwt.map (Result.map (List.map (fun (((v_id, v_title), v_completed), v_order) -> { id = v_id; title = v_title; completed = v_completed; order = v_order })))
end

module Get_todo = struct
  type params = {
    id : int64;
  }
  type row = {
    id : int64;
    title : string;
    completed : bool;
    order : int32;
  }

  let request =
    let open Caqti_request.Infix in
    ((Caqti_type.int64) ->* (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Caqti_type.bool)) (Caqti_type.int32))) "SELECT id, title, completed, todo_order AS \"order\"\nFROM todos\nWHERE id = ?"

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.collect_list request params.id
    |> Lwt.map (Result.map (List.map (fun (((v_id, v_title), v_completed), v_order) -> { id = v_id; title = v_title; completed = v_completed; order = v_order })))
end

module Patch_todo = struct
  type params = {
    title : string option;
    completed : bool option;
    todo_order : int32 option;
    id : int64;
  }
  type row = {
    id : int64;
    title : string;
    completed : bool;
    order : int32;
  }

  let request =
    let open Caqti_request.Infix in
    ((Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.option (Caqti_type.string)) (Caqti_type.option (Caqti_type.bool))) (Caqti_type.option (Caqti_type.int32))) (Caqti_type.int64)) ->* (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Caqti_type.bool)) (Caqti_type.int32))) "UPDATE todos\nSET title = COALESCE(?, title),\n    completed = COALESCE(?, completed),\n    todo_order = COALESCE(?, todo_order)\nWHERE id = ?\nRETURNING todos.id, todos.title, todos.completed, todos.todo_order AS \"order\""

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.collect_list request (((params.title, params.completed), params.todo_order), params.id)
    |> Lwt.map (Result.map (List.map (fun (((v_id, v_title), v_completed), v_order) -> { id = v_id; title = v_title; completed = v_completed; order = v_order })))
end

module Delete_todo = struct
  type params = {
    id : int64;
  }

  let request =
    let open Caqti_request.Infix in
    ((Caqti_type.int64) ->. (Caqti_type.unit)) "DELETE FROM todos WHERE id = ?"

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.exec request params.id
end

module Delete_all_todos = struct
  type params = unit

  let request =
    let open Caqti_request.Infix in
    ((Caqti_type.unit) ->. (Caqti_type.unit)) "DELETE FROM todos"

  let execute (module Db : Caqti_lwt.CONNECTION) (_params : params) =
    Db.exec request ()
end

