(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type todos = {
  id : int64;
  title : string;
  completed : bool;
  todo_order : int32;
}

module Create_todo : sig
  type params = {
    title : string;
    completed : bool;
    todo_order : int32;
  }
  type row = {
    id : int64;
    title : string;
    completed : bool;
    order : int32;
  }

  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

module List_todos : sig
  type params = unit
  type row = {
    id : int64;
    title : string;
    completed : bool;
    order : int32;
  }

  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row list, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  val fold :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    init:'a ->
    f:(row -> 'a -> 'a) ->
    ('a, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

module Get_todo : sig
  type params = {
    id : int64;
  }
  type row = {
    id : int64;
    title : string;
    completed : bool;
    order : int32;
  }

  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row list, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  val fold :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    init:'a ->
    f:(row -> 'a -> 'a) ->
    ('a, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

module Patch_todo : sig
  type params = {
    title : string option;
    completed : bool option;
    todo_order : int32 option;
    id : int64;
  }
  type row = {
    id : int64;
    title : string;
    completed : bool;
    order : int32;
  }

  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row list, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  val fold :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    init:'a ->
    f:(row -> 'a -> 'a) ->
    ('a, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

module Delete_todo : sig
  type params = {
    id : int64;
  }

  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (unit, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

module Delete_all_todos : sig
  type params = unit

  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (unit, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

