(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type todos = {
  id : int64;
  title : string;
  tags : string list;
  completed : bool;
  created_at : Ptime.t;
}

type todo_row = {
  id : int64;
  title : string;
  tags : string list;
  completed : bool;
  created_at : Ptime.t;
}

(** Query [CreateTodo] (returns exactly one row). *)
module CreateTodo : sig
  (** Stable operation name declared in the SQL source. *)
  val operation : string

  type params = {
    title : string;
    tags : string list;
  }
  type row = todo_row

  (** Execute [CreateTodo]. *)
  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  (** Named query descriptor for database helpers. *)
  val query :
    string *
    ((module Caqti_lwt.CONNECTION) ->
     params ->
     (row, [> Caqti_error.call_or_retrieve ]) result Lwt.t)
end

(** Query [ListTodos] (returns zero or more rows). *)
module ListTodos : sig
  (** Stable operation name declared in the SQL source. *)
  val operation : string

  type params = unit
  type row = todo_row

  (** Execute [ListTodos]. *)
  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row list, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  (** Named query descriptor for database helpers. *)
  val query :
    string *
    ((module Caqti_lwt.CONNECTION) ->
     params ->
     (row list, [> Caqti_error.call_or_retrieve ]) result Lwt.t)

  (** Fold rows without materializing the complete result list. *)
  val fold :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    init:'a ->
    f:(row -> 'a -> 'a) ->
    ('a, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

(** Query [ListTodosByIds] (returns zero or more rows). *)
module ListTodosByIds : sig
  (** Stable operation name declared in the SQL source. *)
  val operation : string

  type params = {
    ids : int64 list;
  }
  type row = todo_row

  (** Execute [ListTodosByIds]. *)
  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row list, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  (** Named query descriptor for database helpers. *)
  val query :
    string *
    ((module Caqti_lwt.CONNECTION) ->
     params ->
     (row list, [> Caqti_error.call_or_retrieve ]) result Lwt.t)

  (** Fold rows without materializing the complete result list. *)
  val fold :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    init:'a ->
    f:(row -> 'a -> 'a) ->
    ('a, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

(** Query [CompleteTodo] (returns exactly one row). *)
module CompleteTodo : sig
  (** Stable operation name declared in the SQL source. *)
  val operation : string

  type params = {
    id : int64;
  }
  type row = todo_row

  (** Execute [CompleteTodo]. *)
  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  (** Named query descriptor for database helpers. *)
  val query :
    string *
    ((module Caqti_lwt.CONNECTION) ->
     params ->
     (row, [> Caqti_error.call_or_retrieve ]) result Lwt.t)
end

(** Query [DeleteTodo] (returns the affected-row count). *)
module DeleteTodo : sig
  (** Stable operation name declared in the SQL source. *)
  val operation : string

  type params = {
    id : int64;
  }

  (** Execute [DeleteTodo]. *)
  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (int, [> Caqti_error.call_or_retrieve | `Unsupported ]) result Lwt.t

  (** Named query descriptor for database helpers. *)
  val query :
    string *
    ((module Caqti_lwt.CONNECTION) ->
     params ->
     (int, [> Caqti_error.call_or_retrieve | `Unsupported ]) result Lwt.t)
end

