(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

module Sqlc_array = struct
  let encode_value value =
    let buffer = Buffer.create (String.length value + 2) in
    Buffer.add_char buffer '"';
    String.iter (fun c ->
      if c = '"' || c = '\\' then Buffer.add_char buffer '\\';
      Buffer.add_char buffer c) value;
    Buffer.add_char buffer '"';
    Buffer.contents buffer

  let encode encode_element values =
    "{" ^ String.concat "," (List.map (fun value -> encode_value (encode_element value)) values) ^ "}"

  let decode input =
    let length = String.length input in
    if length < 2 || input.[0] <> '{' || input.[length - 1] <> '}' then
      Error "invalid PostgreSQL array"
    else if length = 2 then Ok []
    else
      let rec element index values =
        if index >= length - 1 then Ok (List.rev values)
        else
          let buffer = Buffer.create 16 in
          let quoted = input.[index] = '"' in
          let rec quoted_value i =
            if i >= length - 1 then Error "unterminated quoted PostgreSQL array element"
            else match input.[i] with
              | '\\' when i + 1 < length - 1 -> Buffer.add_char buffer input.[i + 1]; quoted_value (i + 2)
              | '"' -> separator (i + 1)
              | c -> Buffer.add_char buffer c; quoted_value (i + 1)
          and unquoted_value i =
            if i >= length - 1 || input.[i] = ',' then separator i
            else (Buffer.add_char buffer input.[i]; unquoted_value (i + 1))
          and separator i =
            let value = Buffer.contents buffer in
            if not quoted && String.uppercase_ascii value = "NULL" then Error "NULL array elements are not supported"
            else if i = length - 1 then Ok (List.rev (value :: values))
            else if input.[i] = ',' then element (i + 1) (value :: values)
            else Error "invalid PostgreSQL array separator"
          in
          if quoted then quoted_value (index + 1) else unquoted_value index
      in
      element 1 []

  let codec ~encode_element ~decode_element =
    let rec decode_values acc = function
      | [] -> Ok (List.rev acc)
      | value :: rest ->
          match decode_element value with
          | Ok decoded -> decode_values (decoded :: acc) rest
          | Error error -> Error error
    in
    Caqti_type.custom
      ~encode:(fun values -> Ok (encode encode_element values))
      ~decode:(fun value -> match decode value with Ok values -> decode_values [] values | Error error -> Error error)
      Caqti_type.string
end

type todos = {
  id : int64;
  title : string;
  tags : string list;
  completed : bool;
  created_at : Ptime.t;
}

module Create_todo = struct
  type params = {
    title : string;
    tags : string list;
  }
  type row = {
    id : int64;
    title : string;
    tags : string list;
    completed : bool;
    created_at : Ptime.t;
  }

  let request =
    let open Caqti_request.Infix in
    ((Caqti_type.t2 (Caqti_type.string) (Sqlc_array.codec ~encode_element:(fun x -> x) ~decode_element:(fun x -> Ok x))) ->! (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Sqlc_array.codec ~encode_element:(fun x -> x) ~decode_element:(fun x -> Ok x))) (Caqti_type.bool)) (Caqti_type.ptime))) "INSERT INTO todos (title, tags)\nVALUES (?, ?)\nRETURNING id, title, tags, completed, created_at"

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.find request (params.title, params.tags)
    |> Lwt.map (Result.map (fun ((((v_id, v_title), v_tags), v_completed), v_created_at) -> { id = v_id; title = v_title; tags = v_tags; completed = v_completed; created_at = v_created_at }))
end

module List_todos = struct
  type params = unit
  type row = {
    id : int64;
    title : string;
    tags : string list;
    completed : bool;
    created_at : Ptime.t;
  }

  let request =
    let open Caqti_request.Infix in
    ((Caqti_type.unit) ->* (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Sqlc_array.codec ~encode_element:(fun x -> x) ~decode_element:(fun x -> Ok x))) (Caqti_type.bool)) (Caqti_type.ptime))) "SELECT id, title, tags, completed, created_at\nFROM todos\nORDER BY id"

  let execute (module Db : Caqti_lwt.CONNECTION) (_params : params) =
    Db.collect_list request ()
    |> Lwt.map (Result.map (List.map (fun ((((v_id, v_title), v_tags), v_completed), v_created_at) -> { id = v_id; title = v_title; tags = v_tags; completed = v_completed; created_at = v_created_at })))

  let fold (module Db : Caqti_lwt.CONNECTION) (_params : params) ~init ~f =
    Db.fold request (fun raw acc -> f ((fun ((((v_id, v_title), v_tags), v_completed), v_created_at) -> { id = v_id; title = v_title; tags = v_tags; completed = v_completed; created_at = v_created_at }) raw) acc) () init
end

module List_todos_by_ids = struct
  type params = {
    ids : int64 list;
  }
  type row = {
    id : int64;
    title : string;
    tags : string list;
    completed : bool;
    created_at : Ptime.t;
  }

  let request =
    let open Caqti_request.Infix in
    ((Sqlc_array.codec ~encode_element:Int64.to_string ~decode_element:(fun s -> try Ok (Int64.of_string s) with Failure _ -> Error ("invalid bigint: " ^ s))) ->* (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Sqlc_array.codec ~encode_element:(fun x -> x) ~decode_element:(fun x -> Ok x))) (Caqti_type.bool)) (Caqti_type.ptime))) "SELECT id, title, tags, completed, created_at\nFROM todos\nWHERE id = ANY(?::bigint[])\nORDER BY id"

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.collect_list request params.ids
    |> Lwt.map (Result.map (List.map (fun ((((v_id, v_title), v_tags), v_completed), v_created_at) -> { id = v_id; title = v_title; tags = v_tags; completed = v_completed; created_at = v_created_at })))

  let fold (module Db : Caqti_lwt.CONNECTION) (params : params) ~init ~f =
    Db.fold request (fun raw acc -> f ((fun ((((v_id, v_title), v_tags), v_completed), v_created_at) -> { id = v_id; title = v_title; tags = v_tags; completed = v_completed; created_at = v_created_at }) raw) acc) params.ids init
end

module Complete_todo = struct
  type params = {
    id : int64;
  }
  type row = {
    id : int64;
    title : string;
    tags : string list;
    completed : bool;
    created_at : Ptime.t;
  }

  let request =
    let open Caqti_request.Infix in
    ((Caqti_type.int64) ->! (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Sqlc_array.codec ~encode_element:(fun x -> x) ~decode_element:(fun x -> Ok x))) (Caqti_type.bool)) (Caqti_type.ptime))) "UPDATE todos\nSET completed = true\nWHERE id = ?\nRETURNING id, title, tags, completed, created_at"

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.find request params.id
    |> Lwt.map (Result.map (fun ((((v_id, v_title), v_tags), v_completed), v_created_at) -> { id = v_id; title = v_title; tags = v_tags; completed = v_completed; created_at = v_created_at }))
end

module Delete_todo = struct
  type params = {
    id : int64;
  }

  let request =
    let open Caqti_request.Infix in
    ((Caqti_type.int64) ->. (Caqti_type.unit)) "DELETE FROM todos\nWHERE id = ?"

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.exec_with_affected_count request params.id
end

