(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type todos = {
  id : int64;
  title : string;
  tags : string list;
  completed : bool;
  created_at : Ptime.t;
}

type todo_row = {
  id : int64;
  title : string;
  tags : string list;
  completed : bool;
  created_at : Ptime.t;
}

module CreateTodo = struct
  let operation = "CreateTodo"

  type params = {
    title : string;
    tags : string list;
  }
  type row = todo_row

  let sql =
    {sql|INSERT INTO todos (title, tags)
VALUES (?, ?)
RETURNING id, title, tags, completed, created_at|sql}

  let params_type =
    Caqti_type.t2 (Caqti_type.string) (Sqlc_runtime.Array.codec ~encode_element:(fun x -> x) ~decode_element:(fun x -> Ok x))

  let row_type =
    Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Sqlc_runtime.Array.codec ~encode_element:(fun x -> x) ~decode_element:(fun x -> Ok x))) (Caqti_type.bool)) (Caqti_type.ptime)

  let encode_params (params : params) =
    (params.title, params.tags)

  let decode_row ((((v_id, v_title), v_tags), v_completed), v_created_at) =
    { id = v_id; title = v_title; tags = v_tags; completed = v_completed; created_at = v_created_at }

  let request =
    let open Caqti_request.Infix in
    (params_type ->! row_type) sql

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.find request (encode_params params)
    |> Lwt.map (Result.map decode_row)

  let query = (operation, execute)
end

module ListTodos = struct
  let operation = "ListTodos"

  type params = unit
  type row = todo_row

  let sql =
    {sql|SELECT id, title, tags, completed, created_at
FROM todos
ORDER BY id|sql}

  let params_type =
    Caqti_type.unit

  let row_type =
    Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Sqlc_runtime.Array.codec ~encode_element:(fun x -> x) ~decode_element:(fun x -> Ok x))) (Caqti_type.bool)) (Caqti_type.ptime)

  let encode_params (_params : params) =
    ()

  let decode_row ((((v_id, v_title), v_tags), v_completed), v_created_at) =
    { id = v_id; title = v_title; tags = v_tags; completed = v_completed; created_at = v_created_at }

  let request =
    let open Caqti_request.Infix in
    (params_type ->* row_type) sql

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.collect_list request (encode_params params)
    |> Lwt.map (Result.map (List.map decode_row))

  let fold (module Db : Caqti_lwt.CONNECTION) (params : params) ~init ~f =
    Db.fold request (fun raw acc -> f (decode_row raw) acc) (encode_params params) init

  let query = (operation, execute)
end

module ListTodosByIds = struct
  let operation = "ListTodosByIds"

  type params = {
    ids : int64 list;
  }
  type row = todo_row

  let sql =
    {sql|SELECT id, title, tags, completed, created_at
FROM todos
WHERE id = ANY(?::bigint[])
ORDER BY id|sql}

  let params_type =
    Sqlc_runtime.Array.codec ~encode_element:Int64.to_string ~decode_element:(fun s -> try Ok (Int64.of_string s) with Failure _ -> Error ("invalid bigint: " ^ s))

  let row_type =
    Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Sqlc_runtime.Array.codec ~encode_element:(fun x -> x) ~decode_element:(fun x -> Ok x))) (Caqti_type.bool)) (Caqti_type.ptime)

  let encode_params (params : params) =
    params.ids

  let decode_row ((((v_id, v_title), v_tags), v_completed), v_created_at) =
    { id = v_id; title = v_title; tags = v_tags; completed = v_completed; created_at = v_created_at }

  let request =
    let open Caqti_request.Infix in
    (params_type ->* row_type) sql

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.collect_list request (encode_params params)
    |> Lwt.map (Result.map (List.map decode_row))

  let fold (module Db : Caqti_lwt.CONNECTION) (params : params) ~init ~f =
    Db.fold request (fun raw acc -> f (decode_row raw) acc) (encode_params params) init

  let query = (operation, execute)
end

module CompleteTodo = struct
  let operation = "CompleteTodo"

  type params = {
    id : int64;
  }
  type row = todo_row

  let sql =
    {sql|UPDATE todos
SET completed = true
WHERE id = ?
RETURNING id, title, tags, completed, created_at|sql}

  let params_type =
    Caqti_type.int64

  let row_type =
    Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Sqlc_runtime.Array.codec ~encode_element:(fun x -> x) ~decode_element:(fun x -> Ok x))) (Caqti_type.bool)) (Caqti_type.ptime)

  let encode_params (params : params) =
    params.id

  let decode_row ((((v_id, v_title), v_tags), v_completed), v_created_at) =
    { id = v_id; title = v_title; tags = v_tags; completed = v_completed; created_at = v_created_at }

  let request =
    let open Caqti_request.Infix in
    (params_type ->! row_type) sql

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.find request (encode_params params)
    |> Lwt.map (Result.map decode_row)

  let query = (operation, execute)
end

module DeleteTodo = struct
  let operation = "DeleteTodo"

  type params = {
    id : int64;
  }

  let sql =
    {sql|DELETE FROM todos
WHERE id = ?|sql}

  let params_type =
    Caqti_type.int64

  let encode_params (params : params) =
    params.id

  let request =
    let open Caqti_request.Infix in
    (params_type ->. Caqti_type.unit) sql

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.exec_with_affected_count request (encode_params params)

  let query = (operation, execute)
end

