(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type todos = {
  id : int64;
  title : string;
  tags : string list;
  completed : bool;
  created_at : Ptime.t;
}

module Create_todo : sig
  type params = {
    title : string;
    tags : string list;
  }
  type row = {
    id : int64;
    title : string;
    tags : string list;
    completed : bool;
    created_at : Ptime.t;
  }

  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

module List_todos : sig
  type params = unit
  type row = {
    id : int64;
    title : string;
    tags : string list;
    completed : bool;
    created_at : Ptime.t;
  }

  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row list, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  val fold :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    init:'a ->
    f:(row -> 'a -> 'a) ->
    ('a, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

module List_todos_by_ids : sig
  type params = {
    ids : int64 list;
  }
  type row = {
    id : int64;
    title : string;
    tags : string list;
    completed : bool;
    created_at : Ptime.t;
  }

  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row list, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  val fold :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    init:'a ->
    f:(row -> 'a -> 'a) ->
    ('a, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

module Complete_todo : sig
  type params = {
    id : int64;
  }
  type row = {
    id : int64;
    title : string;
    tags : string list;
    completed : bool;
    created_at : Ptime.t;
  }

  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

module Delete_todo : sig
  type params = {
    id : int64;
  }

  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (int, [> Caqti_error.call_or_retrieve | `Unsupported ]) result Lwt.t
end

