(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

module Array : sig
  val codec :
    encode_element:('a -> string) ->
    decode_element:(string -> ('a, string) result) ->
    'a list Caqti_type.t
end
