(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

module Array = struct
  let encode_value value =
    let buffer = Buffer.create (String.length value + 2) in
    Buffer.add_char buffer '"';
    String.iter (fun c ->
      if c = '"' || c = '\\' then Buffer.add_char buffer '\\';
      Buffer.add_char buffer c) value;
    Buffer.add_char buffer '"';
    Buffer.contents buffer

  let encode encode_element values =
    "{" ^ String.concat "," (List.map (fun value -> encode_value (encode_element value)) values) ^ "}"

  let decode input =
    let length = String.length input in
    if length < 2 || input.[0] <> '{' || input.[length - 1] <> '}' then
      Error "invalid PostgreSQL array"
    else if length = 2 then Ok []
    else
      let rec element index values =
        if index >= length - 1 then Ok (List.rev values)
        else
          let buffer = Buffer.create 16 in
          let quoted = input.[index] = '"' in
          let rec quoted_value i =
            if i >= length - 1 then Error "unterminated quoted PostgreSQL array element"
            else match input.[i] with
              | '\\' when i + 1 < length - 1 -> Buffer.add_char buffer input.[i + 1]; quoted_value (i + 2)
              | '"' -> separator (i + 1)
              | c -> Buffer.add_char buffer c; quoted_value (i + 1)
          and unquoted_value i =
            if i >= length - 1 || input.[i] = ',' then separator i
            else (Buffer.add_char buffer input.[i]; unquoted_value (i + 1))
          and separator i =
            let value = Buffer.contents buffer in
            if not quoted && String.uppercase_ascii value = "NULL" then Error "NULL array elements are not supported"
            else if i = length - 1 then Ok (List.rev (value :: values))
            else if input.[i] = ',' then element (i + 1) (value :: values)
            else Error "invalid PostgreSQL array separator"
          in
          if quoted then quoted_value (index + 1) else unquoted_value index
      in
      element 1 []

  let codec ~encode_element ~decode_element =
    let rec decode_values acc = function
      | [] -> Ok (List.rev acc)
      | value :: rest ->
          match decode_element value with
          | Ok decoded -> decode_values (decoded :: acc) rest
          | Error error -> Error error
    in
    Caqti_type.custom
      ~encode:(fun values -> Ok (encode encode_element values))
      ~decode:(fun value -> match decode value with Ok values -> decode_values [] values | Error error -> Error error)
      Caqti_type.string
end

