package generator

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"github.com/hwu/sqlc-ocaml/internal/plugin"
)

type Override struct {
	DBType   string `json:"db_type"`
	Column   string `json:"column"`
	Nullable *bool  `json:"nullable,omitempty"`
	Type     string `json:"type"`
	Codec    string `json:"codec"`
}
type overrideRule struct {
	dbType, column string
	nullable       *bool
	mapped         mappedType
}
type Options struct {
	Filename  string     `json:"filename"`
	Runtime   string     `json:"runtime"`
	Overrides []Override `json:"overrides"`
}
type gen struct {
	req           *plugin.GenerateRequest
	opts          Options
	overrides     map[string]mappedType
	overrideRules []overrideRule
	enums         map[string]enumInfo
	enumList      []enumInfo
	models        map[string]Record
}

type enumInfo struct {
	Enum     *plugin.Enum
	Schema   string
	TypeName string
}

func Generate(req *plugin.GenerateRequest) (*plugin.GenerateResponse, error) {
	if req.Settings == nil || req.Settings.Engine != "postgresql" {
		return nil, fmt.Errorf("only the postgresql engine is supported")
	}
	opts := Options{Filename: "queries", Runtime: "lwt"}
	if len(req.PluginOptions) > 0 {
		decoder := json.NewDecoder(bytes.NewReader(req.PluginOptions))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&opts); err != nil {
			return nil, fmt.Errorf("invalid plugin options: %w", err)
		}
		var trailing any
		if err := decoder.Decode(&trailing); err != io.EOF {
			if err == nil {
				return nil, fmt.Errorf("invalid plugin options: unexpected trailing JSON value")
			}
			return nil, fmt.Errorf("invalid plugin options trailing data: %w", err)
		}
	}
	if opts.Filename == "" {
		opts.Filename = "queries"
	}
	if opts.Runtime == "" {
		opts.Runtime = "lwt"
	}
	if opts.Runtime != "lwt" && opts.Runtime != "async" {
		return nil, fmt.Errorf("invalid runtime %q (supported: lwt, async)", opts.Runtime)
	}
	opts.Filename = strings.TrimSuffix(strings.TrimSuffix(opts.Filename, ".ml"), ".mli")
	if !validOutputFilename(opts.Filename) {
		return nil, fmt.Errorf("invalid filename %q (expected an OCaml basename such as queries or db_queries)", opts.Filename)
	}
	g := &gen{req: req, opts: opts, overrides: map[string]mappedType{}, enums: map[string]enumInfo{}, models: map[string]Record{}}
	for _, o := range opts.Overrides {
		if (o.DBType == "") == (o.Column == "") || o.Type == "" || o.Codec == "" {
			return nil, fmt.Errorf("each override requires exactly one of db_type or column, plus type and codec")
		}
		rule := overrideRule{dbType: normalizedDBType(o.DBType), column: strings.ToLower(o.Column), nullable: o.Nullable, mapped: mappedType{o.Type, o.Codec}}
		g.overrideRules = append(g.overrideRules, rule)
		if rule.dbType != "" && rule.nullable == nil {
			g.overrides[rule.dbType] = rule.mapped
		}
	}
	if req.Catalog != nil {
		counts := map[string]int{}
		for i, s := range req.Catalog.Schemas {
			if s == nil {
				return nil, fmt.Errorf("catalog schema %d is null", i+1)
			}
			for _, e := range s.Enums {
				if e == nil {
					return nil, fmt.Errorf("catalog schema %q contains a null enum", s.Name)
				}
				counts[strings.ToLower(e.Name)]++
			}
		}
		for _, s := range req.Catalog.Schemas {
			for _, e := range s.Enums {
				typeName := snake(e.Name)
				if counts[strings.ToLower(e.Name)] > 1 {
					typeName = snake(s.Name + "_" + e.Name)
				}
				info := enumInfo{Enum: e, Schema: s.Name, TypeName: typeName}
				g.enumList = append(g.enumList, info)
				g.enums[qualifiedName("", s.Name, e.Name)] = info
				if counts[strings.ToLower(e.Name)] == 1 {
					g.enums[strings.ToLower(e.Name)] = info
				}
			}
		}
	}
	program, err := g.normalize()
	if err != nil {
		return nil, err
	}
	ml, mli, err := g.render(program)
	if err != nil {
		return nil, err
	}
	files := []*plugin.File{{Name: opts.Filename + ".ml", Contents: ml}, {Name: opts.Filename + ".mli", Contents: mli}}
	if programUsesArrays(program) {
		files = append(files,
			&plugin.File{Name: "sqlc_runtime.ml", Contents: []byte(sqlcRuntimeML)},
			&plugin.File{Name: "sqlc_runtime.mli", Contents: []byte(sqlcRuntimeMLI)},
		)
	}
	return &plugin.GenerateResponse{Files: files}, nil
}

func validOutputFilename(name string) bool {
	if name == "" || name[0] < 'a' || name[0] > 'z' {
		return false
	}
	for i := 1; i < len(name); i++ {
		c := name[i]
		if c != '_' && (c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') {
			return false
		}
	}
	return true
}

func (g *gen) render(program Program) ([]byte, []byte, error) {
	var ml, mli bytes.Buffer
	fmt.Fprintf(&ml, "(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)\n\n")
	fmt.Fprintf(&mli, "(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)\n\n")
	g.renderQueryDescriptorTypes(&ml, &mli)
	for _, enum := range program.Enums {
		g.renderEnum(&ml, &mli, enum)
	}
	for _, model := range program.Models {
		renderModel(&ml, &mli, model)
	}
	for _, row := range program.SharedRows {
		renderModel(&ml, &mli, row)
	}
	for _, query := range program.Queries {
		g.renderQuery(&ml, &mli, query)
	}
	return ml.Bytes(), mli.Bytes(), nil
}

func (g *gen) renderQueryDescriptorTypes(ml, mli *bytes.Buffer) {
	connection, fiber := "Caqti_lwt.CONNECTION", "Lwt.t"
	if g.opts.Runtime == "async" {
		connection, fiber = "Caqti_async.CONNECTION", "Async_kernel.Deferred.t"
	}
	definition := fmt.Sprintf(`type one
type many
type exec
type exec_rows

type ('params, 'result, 'cardinality) query =
  | One :
      (string *
       ((module %s) ->
        'params ->
        ('result, Caqti_error.t) result %s)) ->
      ('params, 'result, one) query
  | Many :
      (string *
       ((module %s) ->
        'params ->
        ('result, Caqti_error.t) result %s)) ->
      ('params, 'result, many) query
  | Exec :
      (string *
       ((module %s) ->
        'params ->
        ('result, Caqti_error.t) result %s)) ->
      ('params, 'result, exec) query
  | Exec_rows :
      (string *
       ((module %s) ->
        'params ->
        ('result, Caqti_error.t) result %s)) ->
      ('params, 'result, exec_rows) query

`, connection, fiber, connection, fiber, connection, fiber, connection, fiber)
	fmt.Fprint(ml, definition)
	fmt.Fprint(mli, definition)
}

func programUsesArrays(program Program) bool {
	has := func(record Record) bool {
		for _, field := range record.Fields {
			if field.Type.Element != nil {
				return true
			}
		}
		return false
	}
	for _, model := range program.Models {
		if has(model) {
			return true
		}
	}
	for _, query := range program.Queries {
		if has(query.Params) || query.Row != nil && has(*query.Row) {
			return true
		}
	}
	return false
}

const sqlcRuntimeML = `(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

module Array = struct
  let encode_value value =
    let buffer = Buffer.create (String.length value + 2) in
    Buffer.add_char buffer '"';
    String.iter (fun c ->
      if c = '"' || c = '\\' then Buffer.add_char buffer '\\';
      Buffer.add_char buffer c) value;
    Buffer.add_char buffer '"';
    Buffer.contents buffer

  let encode encode_element values =
    "{" ^ String.concat "," (List.map (fun value -> encode_value (encode_element value)) values) ^ "}"

  let decode input =
    let length = String.length input in
    if length < 2 || input.[0] <> '{' || input.[length - 1] <> '}' then
      Error "invalid PostgreSQL array"
    else if length = 2 then Ok []
    else
      let rec element index values =
        if index >= length - 1 then Ok (List.rev values)
        else
          let buffer = Buffer.create 16 in
          let quoted = input.[index] = '"' in
          let rec quoted_value i =
            if i >= length - 1 then Error "unterminated quoted PostgreSQL array element"
            else match input.[i] with
              | '\\' when i + 1 < length - 1 -> Buffer.add_char buffer input.[i + 1]; quoted_value (i + 2)
              | '"' -> separator (i + 1)
              | c -> Buffer.add_char buffer c; quoted_value (i + 1)
          and unquoted_value i =
            if i >= length - 1 || input.[i] = ',' then separator i
            else (Buffer.add_char buffer input.[i]; unquoted_value (i + 1))
          and separator i =
            let value = Buffer.contents buffer in
            if not quoted && String.uppercase_ascii value = "NULL" then Error "NULL array elements are not supported"
            else if i = length - 1 then Ok (List.rev (value :: values))
            else if input.[i] = ',' then element (i + 1) (value :: values)
            else Error "invalid PostgreSQL array separator"
          in
          if quoted then quoted_value (index + 1) else unquoted_value index
      in
      element 1 []

  let codec ~encode_element ~decode_element =
    let rec decode_values acc = function
      | [] -> Ok (List.rev acc)
      | value :: rest ->
          match decode_element value with
          | Ok decoded -> decode_values (decoded :: acc) rest
          | Error error -> Error error
    in
    Caqti_type.custom
      ~encode:(fun values -> Ok (encode encode_element values))
      ~decode:(fun value -> match decode value with Ok values -> decode_values [] values | Error error -> Error error)
      Caqti_type.string
end

`

const sqlcRuntimeMLI = `(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

module Array : sig
  val codec :
    encode_element:('a -> string) ->
    decode_element:(string -> ('a, string) result) ->
    'a list Caqti_type.t
end
`

func (g *gen) renderEnum(ml, mli *bytes.Buffer, e Enum) {
	tn := e.TypeName
	fmt.Fprintf(ml, "type %s =\n", tn)
	fmt.Fprintf(mli, "type %s =\n", tn)
	for _, v := range e.Values {
		fmt.Fprintf(ml, "  | %s\n", v.Constructor)
		fmt.Fprintf(mli, "  | %s\n", v.Constructor)
	}
	fmt.Fprintf(ml, "\nlet %s_type =\n  Caqti_type.custom\n    ~encode:(fun x -> Ok (match x with\n", tn)
	for _, v := range e.Values {
		fmt.Fprintf(ml, "      | %s -> %q\n", v.Constructor, v.DatabaseName)
	}
	fmt.Fprintln(ml, "    ))\n    ~decode:(function")
	for _, v := range e.Values {
		fmt.Fprintf(ml, "      | %q -> Ok %s\n", v.DatabaseName, v.Constructor)
	}
	fmt.Fprintf(ml, "      | value -> Error (Printf.sprintf \"unknown %s value: %%s\" value))\n    Caqti_type.string\n\n", tn)
	fmt.Fprintf(mli, "\nval %s_type : %s Caqti_type.t\n\n", tn, tn)
}

func uniqueFields(cols []*plugin.Column) ([]string, error) {
	seen := map[string]bool{}
	out := make([]string, len(cols))
	for i, c := range cols {
		if c == nil {
			return nil, fmt.Errorf("field %d has no column metadata", i+1)
		}
		n := snake(c.Name)
		if seen[n] {
			return nil, fmt.Errorf("duplicate field name %q after OCaml normalization", n)
		}
		seen[n] = true
		out[i] = n
	}
	return out, nil
}

func tupleCodec(codecs []string) string {
	if len(codecs) == 0 {
		return "Caqti_type.unit"
	}
	if len(codecs) == 1 {
		return codecs[0]
	}
	r := fmt.Sprintf("Caqti_type.t2 (%s) (%s)", codecs[0], codecs[1])
	for _, c := range codecs[2:] {
		r = fmt.Sprintf("Caqti_type.t2 (%s) (%s)", r, c)
	}
	return r
}
func tupleExpr(xs []string) string {
	if len(xs) == 0 {
		return "()"
	}
	if len(xs) == 1 {
		return xs[0]
	}
	r := "(" + xs[0] + ", " + xs[1] + ")"
	for _, x := range xs[2:] {
		r = "(" + r + ", " + x + ")"
	}
	return r
}
func tuplePattern(xs []string) string { return tupleExpr(xs) }

func (g *gen) renderQuery(ml, mli *bytes.Buffer, q Query) {
	fmt.Fprintf(ml, "module %s = struct\n", q.ModuleName)
	fmt.Fprintf(mli, "(** Query [%s] (%s). *)\n", q.SourceName, cardinalityDescription(q.Cardinality))
	fmt.Fprintf(mli, "module %s : sig\n", q.ModuleName)
	fmt.Fprintf(ml, "  let operation = %q\n\n", q.SourceName)
	fmt.Fprint(mli, "  (** Stable operation name declared in the SQL source. *)\n")
	fmt.Fprint(mli, "  val operation : string\n\n")
	renderRecord(ml, mli, q.Params)
	if q.Row != nil {
		if q.SharedRow != "" {
			fmt.Fprintf(ml, "  type row = %s\n", q.SharedRow)
			fmt.Fprintf(mli, "  type row = %s\n", q.SharedRow)
		} else {
			renderRecord(ml, mli, *q.Row)
		}
	}

	requestOp, method, result := cardinalityRendering(q.Cardinality)
	fmt.Fprintf(ml, "\n  let sql =\n    %s\n\n", ocamlQuotedString(q.SQL))
	fmt.Fprintf(ml, "  let params_type =\n    %s\n\n", bindingCodec(q))
	if q.Row != nil {
		fmt.Fprintf(ml, "  let row_type =\n    %s\n\n", recordCodec(*q.Row))
	}
	paramVars := make([]string, len(q.Bindings))
	for i, binding := range q.Bindings {
		paramVars[i] = "params." + q.Params.Fields[binding.FieldIndex].Name
	}
	input := tupleExpr(paramVars)
	paramArg := "params"
	if len(q.Params.Fields) == 0 {
		paramArg = "_params"
	}
	fmt.Fprintf(ml, "  let encode_params (%s : params) =\n    %s\n\n", paramArg, input)
	if q.Row != nil {
		pattern, record := rowDecoder(*q.Row)
		fmt.Fprintf(ml, "  let decode_row %s =\n    %s\n\n", pattern, record)
	}
	rowType := "Caqti_type.unit"
	if q.Row != nil {
		rowType = "row_type"
	}
	fmt.Fprintf(ml, "  let request =\n    let open Caqti_request.Infix in\n    (params_type %s %s) sql\n\n", requestOp, rowType)
	connection, fiber, mapResult := "Caqti_lwt.CONNECTION", "Lwt.t", "|> Lwt.map (Result.map "
	if g.opts.Runtime == "async" {
		connection, fiber, mapResult = "Caqti_async.CONNECTION", "Async_kernel.Deferred.t", "|> Async_kernel.Deferred.map ~f:(Result.map "
	}
	if q.Cardinality == Exec || q.Cardinality == ExecRows {
		fmt.Fprintf(ml, "  let execute (module Db : %s) (params : params) =\n    Db.%s request (encode_params params)\n", connection, method)
	} else {
		mapper := "decode_row"
		fmt.Fprintf(ml, "  let execute (module Db : %s) (params : params) =\n    Db.%s request (encode_params params)\n    %s", connection, method, mapResult)
		if q.Cardinality == Many {
			fmt.Fprintf(ml, "(List.map %s))\n", mapper)
		} else {
			fmt.Fprintf(ml, "%s)\n", mapper)
		}
		if q.Cardinality == Many {
			fmt.Fprintf(ml, "\n  let fold (module Db : %s) (params : params) ~init ~f =\n    Db.fold request (fun raw acc -> f (decode_row raw) acc) (encode_params params) init\n", connection)
		}
	}
	fmt.Fprint(ml, "\n  let query = (operation, execute)\n")
	fmt.Fprint(ml, "end\n\n")
	errorType := "[> Caqti_error.call_or_retrieve ]"
	if q.Cardinality == ExecRows {
		errorType = "[> Caqti_error.call_or_retrieve | `Unsupported ]"
	}
	fmt.Fprintf(mli, "\n  (** Execute [%s]. *)", q.SourceName)
	fmt.Fprintf(mli, "\n  val execute :\n    (module %s) ->\n    params ->\n    (%s, %s) result %s\n", connection, result, errorType, fiber)
	fmt.Fprint(mli, "\n  (** Named query descriptor for database helpers. *)")
	fmt.Fprintf(mli, "\n  val query :\n    string *\n    ((module %s) ->\n     params ->\n     (%s, %s) result %s)\n", connection, result, errorType, fiber)
	if q.Cardinality == Many {
		fmt.Fprint(mli, "\n  (** Fold rows without materializing the complete result list. *)")
		fmt.Fprintf(mli, "\n  val fold :\n    (module %s) ->\n    params ->\n    init:'a ->\n    f:(row -> 'a -> 'a) ->\n    ('a, %s) result %s\n", connection, errorType, fiber)
	}
	fmt.Fprint(mli, "end\n\n")
}

func ocamlQuotedString(value string) string {
	for i := 0; ; i++ {
		tag := "sql"
		if i > 0 {
			tag = fmt.Sprintf("sql%d", i)
		}
		if !strings.Contains(value, "|"+tag+"}") {
			return "{" + tag + "|" + value + "|" + tag + "}"
		}
	}
}

func cardinalityDescription(cardinality Cardinality) string {
	switch cardinality {
	case One:
		return "returns exactly one row"
	case Many:
		return "returns zero or more rows"
	case ExecRows:
		return "returns the affected-row count"
	default:
		return "executes without returning rows"
	}
}

func renderRecord(ml, mli *bytes.Buffer, record Record) {
	if len(record.Fields) == 0 {
		fmt.Fprintf(ml, "  type %s = unit\n", record.TypeName)
		fmt.Fprintf(mli, "  type %s = unit\n", record.TypeName)
		return
	}
	fmt.Fprintf(ml, "  type %s = {\n", record.TypeName)
	fmt.Fprintf(mli, "  type %s = {\n", record.TypeName)
	for _, field := range record.Fields {
		fmt.Fprintf(ml, "    %s : %s;\n", field.Name, field.Type.Name)
		fmt.Fprintf(mli, "    %s : %s;\n", field.Name, field.Type.Name)
	}
	fmt.Fprintln(ml, "  }")
	fmt.Fprintln(mli, "  }")
}

func renderModel(ml, mli *bytes.Buffer, model Record) {
	fmt.Fprintf(ml, "type %s = {\n", model.TypeName)
	fmt.Fprintf(mli, "type %s = {\n", model.TypeName)
	for _, field := range model.Fields {
		fmt.Fprintf(ml, "  %s : %s;\n", field.Name, field.Type.Name)
		fmt.Fprintf(mli, "  %s : %s;\n", field.Name, field.Type.Name)
	}
	fmt.Fprint(ml, "}\n\n")
	fmt.Fprint(mli, "}\n\n")
}

func recordCodec(record Record) string {
	codecs := flattenedCodecs(record)
	return tupleCodec(codecs)
}

func flattenedCodecs(record Record) []string {
	var codecs []string
	for _, field := range record.Fields {
		if field.Embedded != nil {
			codecs = append(codecs, flattenedCodecs(*field.Embedded)...)
		} else {
			codecs = append(codecs, field.Type.Codec)
		}
	}
	return codecs
}

func bindingCodec(query Query) string {
	codecs := make([]string, len(query.Bindings))
	for i, binding := range query.Bindings {
		codecs[i] = query.Params.Fields[binding.FieldIndex].Type.Codec
	}
	return tupleCodec(codecs)
}

func optionalRecordCodec(record *Record) string {
	if record == nil {
		return "Caqti_type.unit"
	}
	return recordCodec(*record)
}

func rowDecoder(record Record) (string, string) {
	var vars, fields []string
	for _, field := range record.Fields {
		if field.Embedded == nil {
			name := "v_" + field.Name
			vars = append(vars, name)
			fields = append(fields, field.Name+" = "+name)
			continue
		}
		var embeddedFields []string
		for _, nested := range field.Embedded.Fields {
			name := "v_" + field.Name + "_" + nested.Name
			vars = append(vars, name)
			embeddedFields = append(embeddedFields, nested.Name+" = "+name)
		}
		fields = append(fields, field.Name+" = { "+strings.Join(embeddedFields, "; ")+" }")
	}
	return tuplePattern(vars), "{ " + strings.Join(fields, "; ") + " }"
}

func cardinalityRendering(cardinality Cardinality) (requestOp, method, result string) {
	switch cardinality {
	case One:
		return "->!", "find", "row"
	case Many:
		return "->*", "collect_list", "row list"
	case ExecRows:
		return "->.", "exec_with_affected_count", "int"
	default:
		return "->.", "exec", "unit"
	}
}
