package generator

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"github.com/hwu/sqlc-ocaml/internal/plugin"
)

type Override struct {
	DBType   string `json:"db_type"`
	Column   string `json:"column"`
	Nullable *bool  `json:"nullable,omitempty"`
	Type     string `json:"type"`
	Codec    string `json:"codec"`
}
type overrideRule struct {
	dbType, column string
	nullable       *bool
	mapped         mappedType
}
type Options struct {
	Filename  string     `json:"filename"`
	Overrides []Override `json:"overrides"`
}
type gen struct {
	req           *plugin.GenerateRequest
	opts          Options
	overrides     map[string]mappedType
	overrideRules []overrideRule
	enums         map[string]*plugin.Enum
	models        map[string]Record
}

func Generate(req *plugin.GenerateRequest) (*plugin.GenerateResponse, error) {
	if req.Settings == nil || req.Settings.Engine != "postgresql" {
		return nil, fmt.Errorf("only the postgresql engine is supported")
	}
	opts := Options{Filename: "queries"}
	if len(req.PluginOptions) > 0 {
		if err := json.Unmarshal(req.PluginOptions, &opts); err != nil {
			return nil, fmt.Errorf("invalid plugin options: %w", err)
		}
	}
	if opts.Filename == "" {
		opts.Filename = "queries"
	}
	opts.Filename = strings.TrimSuffix(strings.TrimSuffix(opts.Filename, ".ml"), ".mli")
	g := &gen{req: req, opts: opts, overrides: map[string]mappedType{}, enums: map[string]*plugin.Enum{}, models: map[string]Record{}}
	for _, o := range opts.Overrides {
		if (o.DBType == "") == (o.Column == "") || o.Type == "" || o.Codec == "" {
			return nil, fmt.Errorf("each override requires exactly one of db_type or column, plus type and codec")
		}
		rule := overrideRule{dbType: normalizedDBType(o.DBType), column: strings.ToLower(o.Column), nullable: o.Nullable, mapped: mappedType{o.Type, o.Codec}}
		g.overrideRules = append(g.overrideRules, rule)
		if rule.dbType != "" && rule.nullable == nil {
			g.overrides[rule.dbType] = rule.mapped
		}
	}
	if req.Catalog != nil {
		for _, s := range req.Catalog.Schemas {
			for _, e := range s.Enums {
				g.enums[strings.ToLower(e.Name)] = e
			}
		}
	}
	program, err := g.normalize()
	if err != nil {
		return nil, err
	}
	ml, mli, err := g.render(program)
	if err != nil {
		return nil, err
	}
	return &plugin.GenerateResponse{Files: []*plugin.File{{Name: opts.Filename + ".ml", Contents: ml}, {Name: opts.Filename + ".mli", Contents: mli}}}, nil
}

func (g *gen) render(program Program) ([]byte, []byte, error) {
	var ml, mli bytes.Buffer
	fmt.Fprintf(&ml, "(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)\n\n")
	fmt.Fprintf(&mli, "(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)\n\n")
	if programUsesArrays(program) {
		fmt.Fprint(&ml, sqlcArrayModule)
	}
	for _, enum := range program.Enums {
		g.renderEnum(&ml, &mli, enum)
	}
	for _, model := range program.Models {
		renderModel(&ml, &mli, model)
	}
	for _, query := range program.Queries {
		g.renderQuery(&ml, &mli, query)
	}
	return ml.Bytes(), mli.Bytes(), nil
}

func programUsesArrays(program Program) bool {
	has := func(record Record) bool {
		for _, field := range record.Fields {
			if field.Type.Element != nil {
				return true
			}
		}
		return false
	}
	for _, model := range program.Models {
		if has(model) {
			return true
		}
	}
	for _, query := range program.Queries {
		if has(query.Params) || query.Row != nil && has(*query.Row) {
			return true
		}
	}
	return false
}

const sqlcArrayModule = `module Sqlc_array = struct
  let encode_value value =
    let buffer = Buffer.create (String.length value + 2) in
    Buffer.add_char buffer '"';
    String.iter (fun c ->
      if c = '"' || c = '\\' then Buffer.add_char buffer '\\';
      Buffer.add_char buffer c) value;
    Buffer.add_char buffer '"';
    Buffer.contents buffer

  let encode encode_element values =
    "{" ^ String.concat "," (List.map (fun value -> encode_value (encode_element value)) values) ^ "}"

  let decode input =
    let length = String.length input in
    if length < 2 || input.[0] <> '{' || input.[length - 1] <> '}' then
      Error "invalid PostgreSQL array"
    else if length = 2 then Ok []
    else
      let rec element index values =
        if index >= length - 1 then Ok (List.rev values)
        else
          let buffer = Buffer.create 16 in
          let quoted = input.[index] = '"' in
          let rec quoted_value i =
            if i >= length - 1 then Error "unterminated quoted PostgreSQL array element"
            else match input.[i] with
              | '\\' when i + 1 < length - 1 -> Buffer.add_char buffer input.[i + 1]; quoted_value (i + 2)
              | '"' -> separator (i + 1)
              | c -> Buffer.add_char buffer c; quoted_value (i + 1)
          and unquoted_value i =
            if i >= length - 1 || input.[i] = ',' then separator i
            else (Buffer.add_char buffer input.[i]; unquoted_value (i + 1))
          and separator i =
            let value = Buffer.contents buffer in
            if not quoted && String.uppercase_ascii value = "NULL" then Error "NULL array elements are not supported"
            else if i = length - 1 then Ok (List.rev (value :: values))
            else if input.[i] = ',' then element (i + 1) (value :: values)
            else Error "invalid PostgreSQL array separator"
          in
          if quoted then quoted_value (index + 1) else unquoted_value index
      in
      element 1 []

  let codec ~encode_element ~decode_element =
    let rec decode_values acc = function
      | [] -> Ok (List.rev acc)
      | value :: rest ->
          match decode_element value with
          | Ok decoded -> decode_values (decoded :: acc) rest
          | Error error -> Error error
    in
    Caqti_type.custom
      ~encode:(fun values -> Ok (encode encode_element values))
      ~decode:(fun value -> match decode value with Ok values -> decode_values [] values | Error error -> Error error)
      Caqti_type.string
end

`

func (g *gen) renderEnum(ml, mli *bytes.Buffer, e Enum) {
	tn := e.TypeName
	fmt.Fprintf(ml, "type %s =\n", tn)
	fmt.Fprintf(mli, "type %s =\n", tn)
	for _, v := range e.Values {
		fmt.Fprintf(ml, "  | %s\n", v.Constructor)
		fmt.Fprintf(mli, "  | %s\n", v.Constructor)
	}
	fmt.Fprintf(ml, "\nlet %s_type =\n  Caqti_type.custom\n    ~encode:(fun x -> Ok (match x with\n", tn)
	for _, v := range e.Values {
		fmt.Fprintf(ml, "      | %s -> %q\n", v.Constructor, v.DatabaseName)
	}
	fmt.Fprintln(ml, "    ))\n    ~decode:(function")
	for _, v := range e.Values {
		fmt.Fprintf(ml, "      | %q -> Ok %s\n", v.DatabaseName, v.Constructor)
	}
	fmt.Fprintf(ml, "      | value -> Error (Printf.sprintf \"unknown %s value: %%s\" value))\n    Caqti_type.string\n\n", tn)
	fmt.Fprintf(mli, "\nval %s_type : %s Caqti_type.t\n\n", tn, tn)
}

func uniqueFields(cols []*plugin.Column) ([]string, error) {
	seen := map[string]bool{}
	out := make([]string, len(cols))
	for i, c := range cols {
		n := snake(c.Name)
		if seen[n] {
			return nil, fmt.Errorf("duplicate field name %q after OCaml normalization", n)
		}
		seen[n] = true
		out[i] = n
	}
	return out, nil
}

func tupleCodec(codecs []string) string {
	if len(codecs) == 0 {
		return "Caqti_type.unit"
	}
	if len(codecs) == 1 {
		return codecs[0]
	}
	r := fmt.Sprintf("Caqti_type.t2 (%s) (%s)", codecs[0], codecs[1])
	for _, c := range codecs[2:] {
		r = fmt.Sprintf("Caqti_type.t2 (%s) (%s)", r, c)
	}
	return r
}
func tupleExpr(xs []string) string {
	if len(xs) == 0 {
		return "()"
	}
	if len(xs) == 1 {
		return xs[0]
	}
	r := "(" + xs[0] + ", " + xs[1] + ")"
	for _, x := range xs[2:] {
		r = "(" + r + ", " + x + ")"
	}
	return r
}
func tuplePattern(xs []string) string { return tupleExpr(xs) }

// caqtiSQL converts PostgreSQL's $n placeholders to Caqti's portable ? syntax
// and returns their logical parameter numbers in occurrence order.
func caqtiSQL(sql string, params int) (string, []int, error) {
	var b strings.Builder
	var occurrences []int
	for i := 0; i < len(sql); {
		if sql[i] == '\'' || sql[i] == '"' {
			quote := sql[i]
			start := i
			i++
			for i < len(sql) {
				if sql[i] == quote {
					i++
					if i < len(sql) && sql[i] == quote {
						i++
						continue
					}
					break
				}
				i++
			}
			b.WriteString(sql[start:i])
			continue
		}
		if i+1 < len(sql) && sql[i:i+2] == "--" {
			j := strings.IndexByte(sql[i:], '\n')
			if j < 0 {
				b.WriteString(sql[i:])
				i = len(sql)
			} else {
				j += i + 1
				b.WriteString(sql[i:j])
				i = j
			}
			continue
		}
		if i+1 < len(sql) && sql[i:i+2] == "/*" {
			j := strings.Index(sql[i+2:], "*/")
			if j < 0 {
				return "", nil, fmt.Errorf("unterminated SQL block comment")
			}
			j += i + 4
			b.WriteString(sql[i:j])
			i = j
			continue
		}
		if sql[i] == '$' && i+1 < len(sql) && sql[i+1] >= '0' && sql[i+1] <= '9' {
			j := i + 1
			for j < len(sql) && sql[j] >= '0' && sql[j] <= '9' {
				j++
			}
			n, _ := strconv.Atoi(sql[i+1 : j])
			if n < 1 || n > params {
				return "", nil, fmt.Errorf("SQL placeholder $%d has no matching parameter (metadata contains %d)", n, params)
			}
			b.WriteByte('?')
			occurrences = append(occurrences, n)
			i = j
			continue
		}
		b.WriteByte(sql[i])
		i++
	}
	used := make([]bool, params)
	for _, n := range occurrences {
		used[n-1] = true
	}
	for i, ok := range used {
		if !ok {
			return "", nil, fmt.Errorf("query metadata parameter $%d is not used by SQL", i+1)
		}
	}
	return b.String(), occurrences, nil
}

func (g *gen) renderQuery(ml, mli *bytes.Buffer, q Query) {
	fmt.Fprintf(ml, "module %s = struct\n", q.ModuleName)
	fmt.Fprintf(mli, "module %s : sig\n", q.ModuleName)
	renderRecord(ml, mli, q.Params)
	if q.Row != nil {
		renderRecord(ml, mli, *q.Row)
	}

	requestOp, method, result := cardinalityRendering(q.Cardinality)
	fmt.Fprintf(ml, "\n  let request =\n    let open Caqti_request.Infix in\n    ((%s) %s (%s)) %q\n\n", bindingCodec(q), requestOp, optionalRecordCodec(q.Row), q.SQL)
	paramVars := make([]string, len(q.Bindings))
	for i, binding := range q.Bindings {
		paramVars[i] = "params." + q.Params.Fields[binding.FieldIndex].Name
	}
	input := tupleExpr(paramVars)
	paramArg := "params"
	if len(q.Params.Fields) == 0 {
		paramArg = "_params"
	}
	if q.Cardinality == Exec || q.Cardinality == ExecRows {
		fmt.Fprintf(ml, "  let execute (module Db : Caqti_lwt.CONNECTION) (%s : params) =\n    Db.%s request %s\n", paramArg, method, input)
	} else {
		mapper := rowMapper(*q.Row)
		fmt.Fprintf(ml, "  let execute (module Db : Caqti_lwt.CONNECTION) (%s : params) =\n    Db.%s request %s\n    |> Lwt.map (Result.map ", paramArg, method, input)
		if q.Cardinality == Many {
			fmt.Fprintf(ml, "(List.map %s))\n", mapper)
		} else {
			fmt.Fprintf(ml, "%s)\n", mapper)
		}
	}
	fmt.Fprint(ml, "end\n\n")
	errorType := "[> Caqti_error.call_or_retrieve ]"
	if q.Cardinality == ExecRows {
		errorType = "[> Caqti_error.call_or_retrieve | `Unsupported ]"
	}
	fmt.Fprintf(mli, "\n  val execute :\n    (module Caqti_lwt.CONNECTION) ->\n    params ->\n    (%s, %s) result Lwt.t\nend\n\n", result, errorType)
}

func renderRecord(ml, mli *bytes.Buffer, record Record) {
	if len(record.Fields) == 0 {
		fmt.Fprintf(ml, "  type %s = unit\n", record.TypeName)
		fmt.Fprintf(mli, "  type %s = unit\n", record.TypeName)
		return
	}
	fmt.Fprintf(ml, "  type %s = {\n", record.TypeName)
	fmt.Fprintf(mli, "  type %s = {\n", record.TypeName)
	for _, field := range record.Fields {
		fmt.Fprintf(ml, "    %s : %s;\n", field.Name, field.Type.Name)
		fmt.Fprintf(mli, "    %s : %s;\n", field.Name, field.Type.Name)
	}
	fmt.Fprintln(ml, "  }")
	fmt.Fprintln(mli, "  }")
}

func renderModel(ml, mli *bytes.Buffer, model Record) {
	fmt.Fprintf(ml, "type %s = {\n", model.TypeName)
	fmt.Fprintf(mli, "type %s = {\n", model.TypeName)
	for _, field := range model.Fields {
		fmt.Fprintf(ml, "  %s : %s;\n", field.Name, field.Type.Name)
		fmt.Fprintf(mli, "  %s : %s;\n", field.Name, field.Type.Name)
	}
	fmt.Fprint(ml, "}\n\n")
	fmt.Fprint(mli, "}\n\n")
}

func recordCodec(record Record) string {
	codecs := flattenedCodecs(record)
	return tupleCodec(codecs)
}

func flattenedCodecs(record Record) []string {
	var codecs []string
	for _, field := range record.Fields {
		if field.Embedded != nil {
			codecs = append(codecs, flattenedCodecs(*field.Embedded)...)
		} else {
			codecs = append(codecs, field.Type.Codec)
		}
	}
	return codecs
}

func bindingCodec(query Query) string {
	codecs := make([]string, len(query.Bindings))
	for i, binding := range query.Bindings {
		codecs[i] = query.Params.Fields[binding.FieldIndex].Type.Codec
	}
	return tupleCodec(codecs)
}

func optionalRecordCodec(record *Record) string {
	if record == nil {
		return "Caqti_type.unit"
	}
	return recordCodec(*record)
}

func rowMapper(record Record) string {
	var vars, fields []string
	for _, field := range record.Fields {
		if field.Embedded == nil {
			name := "v_" + field.Name
			vars = append(vars, name)
			fields = append(fields, field.Name+" = "+name)
			continue
		}
		var embeddedFields []string
		for _, nested := range field.Embedded.Fields {
			name := "v_" + field.Name + "_" + nested.Name
			vars = append(vars, name)
			embeddedFields = append(embeddedFields, nested.Name+" = "+name)
		}
		fields = append(fields, field.Name+" = { "+strings.Join(embeddedFields, "; ")+" }")
	}
	return "(fun " + tuplePattern(vars) + " -> { " + strings.Join(fields, "; ") + " })"
}

func cardinalityRendering(cardinality Cardinality) (requestOp, method, result string) {
	switch cardinality {
	case One:
		return "->!", "find", "row"
	case Many:
		return "->*", "collect_list", "row list"
	case ExecRows:
		return "->.", "exec_with_affected_count", "int"
	default:
		return "->.", "exec", "unit"
	}
}
