(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type one
type many
type exec
type exec_rows

type ('params, 'result, 'cardinality) query =
  | One :
      (string *
       ((module Caqti_lwt.CONNECTION) ->
        'params ->
        ('result, Caqti_error.t) result Lwt.t)) ->
      ('params, 'result, one) query
  | Many :
      (string *
       ((module Caqti_lwt.CONNECTION) ->
        'params ->
        ('result, Caqti_error.t) result Lwt.t)) ->
      ('params, 'result, many) query
  | Exec :
      (string *
       ((module Caqti_lwt.CONNECTION) ->
        'params ->
        ('result, Caqti_error.t) result Lwt.t)) ->
      ('params, 'result, exec) query
  | Exec_rows :
      (string *
       ((module Caqti_lwt.CONNECTION) ->
        'params ->
        ('result, Caqti_error.t) result Lwt.t)) ->
      ('params, 'result, exec_rows) query

type users = {
  id : int64;
  display_name : string;
  email : Email.t option;
}

type user_row = {
  id : int64;
  display_name : string;
  email : Email.t option;
}

(** Query [CreateUser] (returns exactly one row). *)
module CreateUser : sig
  (** Stable operation name declared in the SQL source. *)
  val operation : string

  type params = {
    display_name : string;
    email : Email.t option;
  }
  type row = user_row

  (** Execute [CreateUser]. *)
  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  (** Named query descriptor for database helpers. *)
  val query : (params, row, one) query
end

(** Query [ListUsers] (returns zero or more rows). *)
module ListUsers : sig
  (** Stable operation name declared in the SQL source. *)
  val operation : string

  type params = unit
  type row = user_row

  (** Execute [ListUsers]. *)
  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row list, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  (** Named query descriptor for database helpers. *)
  val query : (params, row list, many) query

  (** Fold rows without materializing the complete result list. *)
  val fold :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    init:'a ->
    f:(row -> 'a -> 'a) ->
    ('a, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

