(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type users = {
  id : int64;
  display_name : string;
  email : Email.t option;
}

type user_row = {
  id : int64;
  display_name : string;
  email : Email.t option;
}

(** Query [CreateUser] (returns exactly one row). *)
module CreateUser : sig
  type params = {
    display_name : string;
    email : Email.t option;
  }
  type row = user_row

  (** Execute [CreateUser]. *)
  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

(** Query [ListUsers] (returns zero or more rows). *)
module ListUsers : sig
  type params = unit
  type row = user_row

  (** Execute [ListUsers]. *)
  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row list, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  (** Fold rows without materializing the complete result list. *)
  val fold :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    init:'a ->
    f:(row -> 'a -> 'a) ->
    ('a, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

