(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type users = {
  id : int64;
  display_name : string;
  email : Email.t option;
}

type user_row = {
  id : int64;
  display_name : string;
  email : Email.t option;
}

module CreateUser = struct
  type params = {
    display_name : string;
    email : Email.t option;
  }
  type row = user_row

  let sql =
    {sql|INSERT INTO users (display_name, email)
VALUES (?, ?)
RETURNING id, display_name, email|sql}

  let params_type =
    Caqti_type.t2 (Caqti_type.string) (Caqti_type.option (Email.codec))

  let row_type =
    Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Caqti_type.option (Email.codec))

  let encode_params (params : params) =
    (params.display_name, params.email)

  let decode_row ((v_id, v_display_name), v_email) =
    { id = v_id; display_name = v_display_name; email = v_email }

  let request =
    let open Caqti_request.Infix in
    (params_type ->! row_type) sql

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.find request (encode_params params)
    |> Lwt.map (Result.map decode_row)
end

module ListUsers = struct
  type params = unit
  type row = user_row

  let sql =
    {sql|SELECT id, display_name, email
FROM users
ORDER BY id|sql}

  let params_type =
    Caqti_type.unit

  let row_type =
    Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Caqti_type.option (Email.codec))

  let encode_params (_params : params) =
    ()

  let decode_row ((v_id, v_display_name), v_email) =
    { id = v_id; display_name = v_display_name; email = v_email }

  let request =
    let open Caqti_request.Infix in
    (params_type ->* row_type) sql

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.collect_list request (encode_params params)
    |> Lwt.map (Result.map (List.map decode_row))

  let fold (module Db : Caqti_lwt.CONNECTION) (params : params) ~init ~f =
    Db.fold request (fun raw acc -> f (decode_row raw) acc) (encode_params params) init
end

