(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type users = {
  id : int64;
  display_name : string;
  email : Email.t option;
}

module Create_user = struct
  type params = {
    display_name : string;
    email : Email.t option;
  }
  type row = {
    id : int64;
    display_name : string;
    email : Email.t option;
  }

  let sql = "INSERT INTO users (display_name, email)\nVALUES (?, ?)\nRETURNING id, display_name, email"

  let request =
    let open Caqti_request.Infix in
    ((Caqti_type.t2 (Caqti_type.string) (Caqti_type.option (Email.codec))) ->! (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Caqti_type.option (Email.codec)))) sql

  let execute (module Db : Caqti_lwt.CONNECTION) (params : params) =
    Db.find request (params.display_name, params.email)
    |> Lwt.map (Result.map (fun ((v_id, v_display_name), v_email) -> { id = v_id; display_name = v_display_name; email = v_email }))
end

module List_users = struct
  type params = unit
  type row = {
    id : int64;
    display_name : string;
    email : Email.t option;
  }

  let sql = "SELECT id, display_name, email\nFROM users\nORDER BY id"

  let request =
    let open Caqti_request.Infix in
    ((Caqti_type.unit) ->* (Caqti_type.t2 (Caqti_type.t2 (Caqti_type.int64) (Caqti_type.string)) (Caqti_type.option (Email.codec)))) sql

  let execute (module Db : Caqti_lwt.CONNECTION) (_params : params) =
    Db.collect_list request ()
    |> Lwt.map (Result.map (List.map (fun ((v_id, v_display_name), v_email) -> { id = v_id; display_name = v_display_name; email = v_email })))

  let fold (module Db : Caqti_lwt.CONNECTION) (_params : params) ~init ~f =
    Db.fold request (fun raw acc -> f ((fun ((v_id, v_display_name), v_email) -> { id = v_id; display_name = v_display_name; email = v_email }) raw) acc) () init
end

