(* Code generated by sqlc-gen-ocaml. DO NOT EDIT. *)

type users = {
  id : int64;
  display_name : string;
  email : Email.t option;
}

module Create_user : sig
  type params = {
    display_name : string;
    email : Email.t option;
  }
  type row = {
    id : int64;
    display_name : string;
    email : Email.t option;
  }

  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

module List_users : sig
  type params = unit
  type row = {
    id : int64;
    display_name : string;
    email : Email.t option;
  }

  val execute :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    (row list, [> Caqti_error.call_or_retrieve ]) result Lwt.t

  val fold :
    (module Caqti_lwt.CONNECTION) ->
    params ->
    init:'a ->
    f:(row -> 'a -> 'a) ->
    ('a, [> Caqti_error.call_or_retrieve ]) result Lwt.t
end

